# frozen_string_literal: true

require 'ruby-maven'
desc 'Pack jar after compiling classes'
task :compile do
  RubyMaven.exec('prepare-package')
end

desc 'Clean build'
task :clean do
  RubyMaven.exec('clean')
end

task default: [:compile]

require 'rubygems/package_task'
Gem::PackageTask.new(eval(File.read('mygem.gemspec'))) do # rubocop:disable Security/Eval
  desc 'Pack gem'
  task package: [:compile]
end
