require:
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/jar-dependencies.rb

Performance/Casecmp:
  AutoCorrect: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BlockDelimiters:
  IgnoredMethods: []
Style/Documentation:
  Enabled: false
Style/EnvHome:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
