#-*- mode: ruby -*-

inherit 'jar-dependencies:install-ruby-maven:0'

gemspec

# use the current jar dependencies gem
model.dependencies.each do |d|
  if d.artifact_id == 'jar-dependencies'
    d.version = '${jar-dependencies.version}'
  end
end

# vim: syntax=Ruby
