#-*- mode: ruby -*-

inherit 'jar-dependencies:install-ruby-maven:0'

gemspec

# use the current jar dependencies gem
model.dependencies.each do |d|
  if d.artifact_id == 'jar-dependencies'
    d.version = '${jar-dependencies.version}'
  end
end

properties( 'jruby.plugins.version' => '1.0.8',
            'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
