#-*- mode: ruby -*-

inherit 'jar-dependencies:install-ruby-maven:0'

gemspec

properties( 'jruby.plugins.version' => '1.0.8',
            'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
