# frozen_string_literal: true

require 'jars/classpath'
require 'rake/javaextensiontask'

spec = eval File.read('mygem.gemspec') # rubocop:disable Security/Eval
Rake::JavaExtensionTask.new('mygem', spec) do |ext|
  ext.ext_dir = 'ext'
end

task default: [:compile]

require 'rubygems/package_task'
Gem::PackageTask.new(spec) do
  desc 'Pack gem'
  task package: [:compile]
end
