#-*- mode: ruby -*-

inherit 'jar-dependencies:gemspec_with_system_jar:0' do
  # TODO should not be needed with ruby-maven
  relative_path '../Mavenfile'
end

gemspec

# use the current jar dependencies gem
model.dependencies.each do |d|
  if d.artifact_id == 'jar-dependencies'
    d.version = '${jar-dependencies.version}'
  end
end

properties( 'gem.home' => '${project.basedir}/../../rubygems',
            'gem.path' => '${gem.home}' )

# vim: syntax=Ruby
