#-*- mode: ruby -*-

inherit 'jar-dependencies:gemspec_with_system_jar:0'

gemspec

properties( 'gem.home' => '${project.basedir}/../pkg/rubygems',
            'gem.path' => '${gem.home}',
            'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
