#-*- mode: ruby -*-

id 'jar-dependencies:gemspec_with_system_jar:0'

packaging 'pom'

name 'aggregator'

modules ['gem', 'verify']

properties( 'gem.home' => '${project.basedir}/../rubygems',
            'gem.path' => '${gem.home}' )

jruby_plugin :gem, '${jruby.plugins.version}' do
  execute_goal :initialize
end

# vim: syntax=Ruby
