#-*- mode: ruby -*-

id 'jar-dependencies:gemspecs:0'

packaging 'pom'

name 'aggregator'

modules ['first', 'second', 'third', 'forth', 'verify']

properties( 'gem.home' => '${project.basedir}/pkg',
            'gem.path' => '${gem.home}' )

build do
  directory 'pkg'
end

# this is ahack to avoid downloading ruby-maven on the side
# TODO tell gem-maven-plugin to set JARS_SKIP=true to avoid such hack
repository :id => 'rubygems-releases', :url => 'http://rubygems-proxy.torquebox.org/releases'
gem 'ruby-maven', '${ruby-maven.version}'
gem 'ruby-maven-libs', '3.3.3'
jruby_plugin :gem, '${jruby.plugins.version}' do
  execute_goal :initialize
end

# vim: syntax=Ruby
