#-*- mode: ruby -*-

id 'jar-dependencies:install-ruby-maven:0'

packaging 'pom'

modules ['gem', 'verify']

properties( 'tesla.dump.pom' => 'pom.xml',
            'tesla.dump.readonly' => true )

# vim: syntax=Ruby
