#-*- mode: ruby -*-

inherit 'jar-dependencies:gemspecs:0'

gem 'jar-dependencies', '${jar-dependencies.version}'

gemspec

properties( 'gem.home' => '${basedir}/../pkg',
            'gem.path' => '${gem.home}')

# vim: syntax=Ruby
